#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Compatible with Python 2 and Python 3
# Run from the project root: python updatelist.py

import os

VIDEOS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'videos')
OUTPUT_FILE = os.path.join(VIDEOS_DIR, 'videolist.js')
EXTENSIONS = ('.mp4', '.mov', '.avi', '.webm', '.ogg')

def main():
    files = []
    for root, dirs, filenames in os.walk(VIDEOS_DIR):
        dirs.sort()
        for f in sorted(filenames):
            if f.lower().endswith(EXTENSIONS):
                rel = os.path.relpath(os.path.join(root, f), VIDEOS_DIR)
                rel = rel.replace(os.sep, '/')
                files.append(rel)

    if not files:
        print('No video files found in videos/')
        return

    entries = ', '.join(["'" + f + "'" for f in files])
    content = '// Auto-generated by updatelist.py — do not edit manually\nvar PLAYLIST = [' + entries + '];\n'

    with open(OUTPUT_FILE, 'w') as out:
        out.write(content)

    print('Written ' + OUTPUT_FILE)
    for f in files:
        print('  ' + f)

main()
